# Generated by Django 5.1.2 on 2024-10-17 15:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_file', models.ImageField(upload_to='imag/')),
                ('name_first', models.CharField(max_length=255)),
                ('tel_num', models.IntegerField()),
                ('us_email', models.EmailField(max_length=254)),
                ('social_net', models.CharField(max_length=45)),
                ('subs', models.CharField(max_length=45)),
                ('num', models.IntegerField()),
                ('tem', models.CharField(max_length=45)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicat', models.CharField(default='Отправлено', max_length=45)),
                ('kol', models.IntegerField(default=0)),
                ('blog', models.ManyToManyField(related_name='blog', to='dune_freelance.bloger')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_nach', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_konec', models.DateTimeField(default=django.utils.timezone.now)),
                ('format', models.CharField(default='Н/Д', max_length=500)),
                ('work_url', models.URLField()),
                ('kol_p', models.IntegerField(default=0)),
                ('projects_post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='apl_blog_us', to='dune_freelance.applications')),
            ],
        ),
        migrations.CreateModel(
            name='Projects_men',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('photo', models.ImageField(upload_to='imag/')),
                ('pay', models.IntegerField()),
                ('men_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_start', models.DateTimeField()),
                ('date_finish', models.DateTimeField()),
                ('social_category', models.CharField(max_length=45)),
                ('pay_category', models.CharField(max_length=10)),
                ('stat', models.CharField(max_length=15)),
                ('us_manager', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='applications',
            name='pr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pr', to='dune_freelance.projects_men'),
        ),
    ]
